### ISSUE TITLE
Dark menu bar: icon is not visible unless clicked

### ISSUE THREAD

**Issue by delebedev** [czechboy0/Buildasaur#106]
Now it is completely invisible, if you click it it shows up:
<img width="205" alt="screenshot 2015-07-22 20 06 40" src="https://cloud.githubusercontent.com/assets/829783/8834646/53a96e02-30ad-11e5-9d85-dff2c6ec6313.png">

**Comment by czechboy0** [comment]
What version are you using? I'll need to go back to the old tag and fix it there, the newest version only supports Xcode 7 and up :)

**Comment by czechboy0** [comment]
The last Xcode 6 compatible version is 0.2.9.

**Comment by delebedev** [comment]
I've used latest available release actually.

**Comment by czechboy0** [comment]
Latest release (0.2.9) or beta release (0.3b2)? Just so that I know which to fix :)

**Comment by delebedev** [comment]
Sorry haven't seen 0.3b2, I use https://github.com/czechboy0/Buildasaur/releases/tag/v0.2.9

**Comment by czechboy0** [comment]
But again, **only** update to 0.3 if you're using Xcode 7 in your Xcode Server.

**Comment by czechboy0** [comment]
This is fixed in 0.3 and judging from #107 you're using 0.3 beta already. (Just tested on dark mode and works ok, but you're right that dark mode was broken in 0.2.9).
