### ISSUE TITLE
0.29: The server SSH fingerprint failed to verify.

### ISSUE THREAD

**Issue by delebedev** [czechboy0/Buildasaur#107]
No idea what's happening actually, logs (I definitely have write access)

```
[VERBOSE]: Finished blueprint validation with success: false, error: Optional(Error Domain=com.honzadvorsky.Buildasaur Code=0 "The server SSH fingerprint failed to verify." UserInfo=0x61000046bc80 {NSLocalizedDescription=The server SSH fingerprint failed to verify.})
[ERROR]: Checking github availability error: Error Domain=com.honzadvorsky.Buildasaur Code=0 "The server SSH fingerprint failed to verify." UserInfo=0x61000046bc80 {NSLocalizedDescription=The server SSH fingerprint failed to verify.}
```

```
⇒  ssh -T git@github.com
Hi garnett! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by czechboy0** [comment]
This seems like you're using an old version of Buildasaur (pre-0.3) with Xcode 7 in Xcode Server. If that's the case, please look at the last beta release 0.3b2, that should work :) 

Xcode Server introduced fingerprint validation to their API in Xcode 7. Old Buildasaur version can't yet handle that.

**Comment by delebedev** [comment]
It is exactly the case. However I cannot build 0.3 with latest (yesterday's) Xcode :cry: and there is no binary

**Comment by czechboy0** [comment]
Oh crap, in that case let me try to fix that and then you'll have to build from code (a bug in CocoaPods is not letting me archive in Xcode 7). Beta FTW

**Comment by czechboy0** [comment]
Fixed, try this one: https://github.com/czechboy0/Buildasaur/releases/tag/v0.3-beta3

**Comment by czechboy0** [comment]
Let me know if that works for you! :)

**Comment by czechboy0** [comment]
@garnett Whenever you have a sec, please ping me whether your issue got resolved with the latest beta, thanks! :wink:

**Comment by delebedev** [comment]
@czechboy0 works fine with latest beta4 release!

**Comment by czechboy0** [comment]
:+1:
