### ISSUE TITLE
Allow automatic start of builds after pull request has been opened

### ISSUE THREAD

**Issue by mdio** [czechboy0/Buildasaur#11]
Hi, Honza.
You probably already anticipated it, so here's the request for the possibility to remove the "lttm barrier". :)

We're using your awesome tool for our pull requests which go to private repositories with only trusted users to access them.
Forgetting to type lttm leads to no hints at all of any failed tests.

Right now we simply return isEnabled: true from isBotEnabled() in our own build of Buildasaur but it would be nice if you could incorporate that as an option so we won't have to modify your code after each update.

**Comment by czechboy0** [comment]
Hey Michael,

thanks for filing the first Buildasaur issue! :) Yeah making the lttm barrier optional makes sense, I'll look into allowing for customization of the bot enabled state from the UI or from a config file. Let me know if you have any more issues/ideas!

**Comment by mdio** [comment]
Not our use case but others may benifit from the possibility to set this individually per repository (see my other issue about multi repo support ;).

**Comment by czechboy0** [comment]
Yeah it would definitely be configurable on a per-[Syncer](https://github.com/czechboy0/Buildasaur/blob/master/Buildasaur/HDGitHubXCBotSyncer.swift) basis.

**Comment by czechboy0** [comment]
Hey Michael,

optional lttm is in, checkout the latest release: https://github.com/czechboy0/Buildasaur/releases/tag/v0.2.5

You should now be able to just download the .app from the release page and use that. In the UI is now a switch where you can disable the "lttm" barrier - thanks for that name, by the way :)

Let me know if this works for your team and keep the ideas coming!

**Comment by mdio** [comment]
The switch to disable the lttm barrier works very good.
Thanks for that!

Regarding ideas... well besides the mutli repo support we have everything we need right now.
You could have a look at the [GitHub Pull Request Builder Plugin](https://github.com/jenkinsci/ghprb-plugin) (which we used before moving to Swift and Xcode Server) and draw some ideas from that if you haven't already.
