### ISSUE TITLE
SSH error occurs when pushing a commit to a branch with an active PR while first build is running

### ISSUE THREAD

**Issue by voidrender** [czechboy0/Buildasaur#112]
Steps to reproduce:
- Open a Pull Request.
- While the Builda bot is running the first integration, but before it has completed, push a new commit to the branch for which the PR was opened.
- Observe that the first build is cancelled, and the second build fails with a checkout error:

```
[ERROR]: Integration #2 finished with a checkout error - please check that your SSH keys setup in Buildasaur are correct! If you need to fix them, please do so and then you need to recreate the bot - e.g. by closing the Pull Request, waiting for a sync (bot will disappear) and then reopening the Pull Request - should do the job!
```

Workaround:
- Stop and start Buildasaur.
- Close the PR.
- Wait for bot to be deleted, and then reopen PR.

I have logs of this (6 KB) if needed.

**Comment by czechboy0** [comment]
- Does this not happen when you let the first integration finish before you push again?
- Have you tried doing this between the second and third integration? There might be some weirdness in my logic when it comes to the first integration not being finished.

Thanks for reporting this! Will try to reproduce and fix in the next couple of days.

**Comment by voidrender** [comment]
1) This does not happen when we let the first integration finish. Works as expected in that scenario.
2) We have not tried this between the second and third integration, but I will keep an eye on that scenario.

Thanks! Really like Buildasaur. My team has a pretty PR-heavy workflow, so it saves us a lot of time.

**Comment by czechboy0** [comment]
Happy to hear that! :+1:

**Comment by voidrender** [comment]
I happened to run into the scenario you mentioned in the second bullet point, so I tried it out and it didn't fail, so this seems to be limited to the first integration only.

**Comment by czechboy0** [comment]
Cool, that's really helpful, thanks!

**Comment by voidrender** [comment]
It might be worth noting that when it successfully cancels an integration to start the next one, that fact doesn't seem to be communicated to GitHub. It continues to show as "building...".
![builda-112](https://cloud.githubusercontent.com/assets/1653961/9398140/b1ab0396-4758-11e5-8526-4327ea3bb694.png)

**Comment by czechboy0** [comment]
Yeah that's a known bug, would you mind reporting that as a separate issue? That's not trivial to fix but I'd like to find a way to do it.

**Comment by voidrender** [comment]
Sure.

**Comment by czechboy0** [comment]
Hi @ioveracker - I tried for an hour to reproduce this but unfortunately I couldn't. Even when I push additional commits to an existing PR which has a running Bot, the first integration gets cancelled (as it should) and the next one is kicked-off and succeeds. Can you please make sure to update to the latest Buildasaur (0.4.0), the latest Xcode (7 - release) and OS X Server (5 release) - and try again? If the issue persists, I'll keep digging. I just want to make sure it's not something that was broken in Xcode Server. Thanks! :+1:

**Comment by czechboy0** [comment]
Hey @ioveracker, could you please give the new version a try and let me know if this persists? At the moment I don't know what I can do about this, thanks! :+1:

**Comment by voidrender** [comment]
Sure! Sorry for the delay. Once I finish getting Buildasaur running on El Capitan I'll give this a shot and report back.

**Comment by czechboy0** [comment]
No worries :+1:

**Comment by voidrender** [comment]
This no longer occurs in 0.6.1. Instead, the existing integration is canceled and a new one is created.

**Comment by czechboy0** [comment]
Good, that's intended behavior :+1:
