### ISSUE TITLE
Redundant integration step reporting

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#113]
Well, this is a really small issue, but now that GitHub have improved their support for CI services, "Buildasaur" will be printed twice when displaying integration step. I demand that the "Buildasaur:" part is removed from output! :rage2: 

![skarmavbild 2015-08-20 kl 12 22 39](https://cloud.githubusercontent.com/assets/1607453/9381320/85325f2a-4736-11e5-88cd-9792495ad1fa.png)

**Comment by czechboy0** [comment]
I would very much welcome a PR with this fix :wink:

**Comment by joelekstrom** [comment]
Ask, and you shall receive.
