### ISSUE TITLE
what does LTTM mean?

### ISSUE THREAD

**Issue by skydivedan** [czechboy0/Buildasaur#117]
Sorry for the silly question, but I can't figure this acronym.

At work, we use "LGTM" for "Looks good to me", when approving a pull request. So, I assume it's something close, but I can't figure out what that first "T" is.

**Comment by czechboy0** [comment]
Good question, I actually don't have it spelled out in the readme. It means "looks testable to me" and the rationale is described [here](https://github.com/czechboy0/Buildasaur/blob/gladiolus/README.md#unlock-the-lttm-barrier). Basically, our tests take about 20mins, so we want to make sure the human reviewer is happy with the code before it gets tested.

**Comment by czechboy0** [comment]
And yes, we derived it from "lgtm".

**Comment by skydivedan** [comment]
ok, thanks for the clarification!
