### ISSUE TITLE
Can't setup using a project that was checked out via SSH

### ISSUE THREAD

**Issue by nadavhart** [czechboy0/Buildasaur#127]
Hey @czechboy0. First of all, this is a beautiful project! thank you :)

I'm trying to set it up on our CI mac mini (using Xcode 7, OS X 10.10.5, OS X Server 5.0.0, Buildasaur 0.4.0), but although I checked out the project via SSH, I'm seeing this error when trying to add my project in the initial setup "Couldn't add Xcode project at path file:///path/to/project/workspace.xcworkspace, error: Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH."

I've tried different versions of Buildasaur, tried deleting and re-adding the repo, re-cloning it, replacing ssh keys, nothing. Am I missing something? If not, is there a work around to using the workspace as the ssh reference for Builda?

Thanks!

**Comment by FlashGen** [comment]
I have the same issue. Could it be because I checked out my project outside of Xcode and Buildasaur is looking for a specific flag Xcode sets?

**Comment by czechboy0** [comment]
Hey guys, sorry to hear you're having this issue. 

Buildasaur is looking for a file called `Buildasaur.xccheckout`, which Xcode should create inside of the workspace when opened. Try opening your cloned project on Xcode and possibly just creating one Bot manually and then trying Buildasaur again. This could force Xcode to create the xccheckout file. 

I haven't yet found a way to force Xcode to create this file on demand, but as I see this issue, I'll look at a better way to fix this problem. 

Thanks for reporting it and please try the steps above and please let me know if it helped.

**Comment by czechboy0** [comment]
Relates to #89

**Comment by nadavhart** [comment]
Hey (and apologies for the delay in answering). 

@czechboy0, I've checked and the xccheckout file exists in the repo inside the xcworkspace file, but as it is was already committed in the past, the fact that I clone the repo via ssh doesn't reflect in it (it only contains the https url). I guess that this is the root of the issue (at least on my end). I tried forcing Xcode to create a new xccheckout file by creating a bot, changing origin and pulling after removing the file and so forth, but nothing makes Xcode regenerate that file. Any way you can let me know what's the required info and I'll manually edit the existing xccheckout file?

Thanks!

**Comment by czechboy0** [comment]
@nadavhart Oh if you already have a checkout file (should be in the `.xcworkspace/xcshareddata/PROJECT.xccheckout`), just edit the remote URL from https to ssh - just search for `https` in the checkout file, very easy to find. Then start Xcode again and hopefully that should help (Buildasaur will def be happy).

**Comment by nadavhart** [comment]
I decided to stop being lazy, reviewed the project.swift and found out exactly that a minute ago :) basically I just had to change the value for IDESourceControlProjectURL, and to make sure to add it without the "git@" prefix. Everything works well and setup is on it's way. Thank you!

**Comment by czechboy0** [comment]
:+1: Amazing. I still need to find out whether there's a good way to make Xcode (re)generate the checkout file. Glad you got this working though!
