### ISSUE TITLE
Analyzer Warnings are Not considered Errors

### ISSUE THREAD

**Issue by grantjk** [czechboy0/Buildasaur#128]
When the static analyzer fails on the server, the report sent to Github should be a failure status. Currently, the status is reported as green, with no mention of the analyzer errors
### Example PR with failing analyzer

![screenshot 2015-09-24 22 02 20](https://cloud.githubusercontent.com/assets/1066132/10091360/4e50e934-6308-11e5-8f77-1fbd36061ed2.png)
### PR Status Message

![screenshot 2015-09-24 22 02 47](https://cloud.githubusercontent.com/assets/1066132/10091361/50b973a8-6308-11e5-9340-457b15300dbc.png)

**Comment by grantjk** [comment]
I realized later tonight that analyzer warnings are reported if there are no other warnings.  IMO, I still think that if the build comes back with warnings and/or analyzer warnings, this should be posted as a "failed" state to Github so the red `x` shows up rather than the green checkmark

**Comment by czechboy0** [comment]
Would you consider a warning a reason to also fail? Or would you treat analyzer warnings and warnings differently?

You can see [here](https://github.com/czechboy0/Buildasaur/blob/master/BuildaKit/SyncPairResolver.swift#L268) that `warnings` and `analyzer warnings` as still treated as success (I've seen situations when migrating Xcode's, e.g., when a couple of warnings will be in the project for a couple of days and there's not much you can do about it). I just added analyzer warnings there as well, but I don't have any strong feelings about it - I could move it to the failure case as well.

So again - is that what you expected? Analyzer warnings being treated as a failure and warnings as success?

**Comment by grantjk** [comment]
Ha! That probably depends who you ask. Like the dot-syntax vs. brackets debate.

Personally, we try to keep all projects with 0 warnings overall, so any warning to me is considered a regression / error. And when I see the green checkmark and Github's big green buttons, it indicates to me that everything is perfect.

Analyzer warnings, however, should definitely be considered failures. Those are things like "You forgot to call `super` in `viewDidLoad` which has significant implications.

**Comment by czechboy0** [comment]
Fair enough. I don't just want to change it in code, so I'll probably add a way to configure how to treat warnings/analyzer warnings and probably default to the existing behavior, with the option to switch to `strict` mode.

**Comment by czechboy0** [comment]
Moving to #132.
