### ISSUE TITLE
Bots Initial Integrations Are Not Triggered

### ISSUE THREAD

**Issue by grantjk** [czechboy0/Buildasaur#129]
With our setup, a bot is created fine for each PR, but the first integration is never created. We have to manually trigger the first integration, at which point, future integrations are handled perfect.

I've attached an image of our Bot config below and we're using SSH to access GH.

![screenshot 2015-09-24 22 09 11](https://cloud.githubusercontent.com/assets/1066132/10091420/1ea4376c-6309-11e5-95b4-4dc4054139c0.png)

**Comment by czechboy0** [comment]
Hmm, that's weird. 
1. What is your sync interval? Did you keep it at 15 seconds or did you make it longer? There is a caveat that actually the bot _creation_ and the kick-off of its first integration are _not_ done in the same sync pass, so you'd have to wait another `sync interval` seconds for Buildasaur to kick it off. Please make sure you waited at least that long and let me know if no integration is still kicked off (you can see it in Xcode in the Report Navigator).

**Comment by czechboy0** [comment]
Wait, I just remembered - are you sure you don't have the [lttm barrier](https://github.com/czechboy0/Buildasaur#unlock-the-lttm-barrier) enabled? That would cause Buildasaur to wait for a comment saying `lttm` to start testing. You can verify by hovering over the orange dot and reading the message. If it shows something like this below, you have the `lttm barrier` enabled - which you can disable easily in Buildasaur's UI (at the bottom, right below the `Start` button). 

<img width="322" alt="screenshot 2015-09-25 11 39 48" src="https://cloud.githubusercontent.com/assets/2182121/10098600/654bfae4-637a-11e5-9cc6-1d0c9d11317a.png">

**Comment by grantjk** [comment]
That was it!  Oops! Thanks!

That wasn't the default on the previous versions of the app, so I wasn't expecting it. Glad to see #130 go in!

:+1:

**Comment by czechboy0** [comment]
Okay, sorry about that. But at least #130 fixes that for others. To be honest, I should have realized this earlier, but I was just closed in my little world where `lttm` was commonplace.

Anyway, the default is `off` now, so this shouldn't happen again.
