### ISSUE TITLE
GIT Warning

### ISSUE THREAD

**Issue by Brett-Best** [czechboy0/Buildasaur#136]
`An error occurred updating existing checkout. Falling back to a clean checkout.`
My normal bots produce the above warning after Buildasaur runs a PR bot.

**Comment by czechboy0** [comment]
If you push to the branch of this PR again, and another integration happens, does that also have this warning? I've seen this on the 1st integration only, so I'm wondering if it goes away with more integrations or not.

**Comment by czechboy0** [comment]
Can you reliably reproduce this on every new PR Bot created by Buildasaur?

**Comment by Brett-Best** [comment]
@czechboy0 once buildasaur does a PR bot the first time normal bots run it happens.

**Comment by Brett-Best** [comment]
Something to do with my creation of the xccheckout file I wonder.

**Comment by czechboy0** [comment]
Right, maybe it's that, yeah. Are you sure you modified all the values properly? Maybe going through it again to see might be worth it. Because I'm not seeing this error at all on my Mac.

**Comment by Brett-Best** [comment]
@czechboy0 yes I replaced all of the values correctly.

**Comment by czechboy0** [comment]
Hey @Brett-Best, is this still happening?

**Comment by Brett-Best** [comment]
@czechboy0 yes it is.

**Comment by czechboy0** [comment]
@Brett-Best Can you please read through the conversation in #140, which got resolved. Maybe creating the checkout file by hand won't be the best way to go. In #140, there are two possible fixes mentioned: 
- upgrade Buildasaur to 0.5.0, which now also parses `xcscmblueprint` files
- if that doesn't help, if possible, open your project in Xcode 6.4, which should create the old checkout file for you

Before you do either one, I suggest you remove your existing checkout file (the one created by hand), which might turn out to be corrupt - I think that's causing this warning.

Please let me know what helped, thanks! :+1:

**Comment by czechboy0** [comment]
Hey @Brett-Best, can you please try the above? Otherwise there's nothing I can do about it at the moment.

**Comment by Brett-Best** [comment]
@czechboy0 it seems it may be resolved.
