### ISSUE TITLE
Password Storage

### ISSUE THREAD

**Issue by Brett-Best** [czechboy0/Buildasaur#137]
Currently credentials are stored in plain text.

Change to use the keychain instead.

**Comment by czechboy0** [comment]
Just FYI, I'm doing huge refactoring in https://github.com/czechboy0/Buildasaur/pull/138, so you might want to hold off on this task for a couple of days. Otherwise it might be a pain to even merge it :)

**Comment by Brett-Best** [comment]
@czechboy0 that's fine :) will do.

**Comment by Brett-Best** [comment]
@czechboy0 is this good to go now?

**Comment by czechboy0** [comment]
Yes, the big refactoring has been merged. Feel free to use this issue to track progress and ideas, let's discuss how you'll structure the change before you start so that we consider all aspects of it :)

**Comment by czechboy0** [comment]
FYI, @Brett-Best. I'm taking over this one. I need it done for more work that's queued.

**Comment by czechboy0** [comment]
This has been merged into the v0.8 development branch, so don't expect it in v0.7 yet. Closing to not be in the list of open issues though :)
