### ISSUE TITLE
Can't add Xcode Project/Workspace

### ISSUE THREAD

**Issue by concertman** [czechboy0/Buildasaur#140]
Greetings! we are really loving Buildasaur. Just having an issue getting a project set up.

on 0.4.0 when I try to add my workspace I get the following message.

> Couldn't add Xcode project at path file:///Users/coder/Documents/Projects/iOS/project.xcworkspace, error: Cannot find the Checkout file, please make sure to open this project in Xcode at least once (it will generate the required Checkout file). Then try again..

I follow those steps and still get the same error. I've also tried the steps listed in #127 (just in case) and still couldn't get it to work. I've checked for the presence of `.xcworkspace/xcshareddata/PROJECT.xccheckout` and there's not one there in the .xcworkspace or in .xcodeproj.

I'm on Xcode 7.

Any suggestions on what I can do to resolve this?

**Comment by czechboy0** [comment]
Hi @concertman, sorry that you're having this issue. Xcode 7 seems to have changed the way they generate the checkout file (to the point that I'm not sure when it generates it, if at all). 

I am still in the process of trying to figure out what changed, because all the users who have been using Buildasaur from before Xcode 7 are fine (the fine is there and checked into their repo). 

There _is_ a way to create the file manually, even though it's a bit fiddly, I described it [here](https://github.com/czechboy0/Buildasaur/issues/89#issuecomment-143238992). The person I wrote it for got it working that way.

Let me know what you end up doing, I'd love to help as much as I can.

**Comment by czechboy0** [comment]
Also, just to check, does the file `.xcworkspace/xcshareddata/PROJECT.xcscmblueprint` (different file extension) exist? I think that's the new format that Xcode is using.

**Comment by Raman148** [comment]
If you have the luxury, simply open the project in Xcode6.4 and then in Xcode 7. 
Opening it in 6.4 will auto generate this file

**Comment by czechboy0** [comment]
@Raman148 Oh have you actually tried that? Amazing, I was wondering whether that would help. @concertman This is definitely a better solution than having to hack the checkout file yourself :) 

Thanks @Raman148!

**Comment by Raman148** [comment]
@czechboy0 Confirmed on my end, I had this issue this morning when migrating.

Thank you!

**Comment by czechboy0** [comment]
@Raman148 Thanks again, I'll recommend this as a troubleshooting step before I can make Xcode generate these files for us reliably.

Also, in #141 I just added support for `.xcscmblueprint` files, which, I believe, is what Xcode 7 prefers to generate (sometimes).

**Comment by czechboy0** [comment]
@concertman Please try what @Raman148 suggested and let me know if that fixed it for you, thaaaaanks! :wink:

**Comment by czechboy0** [comment]
Also, @concertman please update to [0.5.0](https://github.com/czechboy0/Buildasaur/releases/tag/v0.5.0) before you try again, maybe you at least had an `xcscmblueprint` file there, which would now get picked up by Buildasaur, thanks!

**Comment by concertman** [comment]
@czechboy0 I just tried 0.5.0 locally and it seems to work. I'm about to try it on my Xcode CI server to confirm. I'll post back once I have done that.

**Comment by czechboy0** [comment]
Ha, if just upgrading to 0.5.0 alone fixed it, it means you had the newer
format checkout file there (xcscmblueprint). Make sure to keep that checked
in in git. Feel free to ping me if you need any help setting Buildasaur up!

**Comment by concertman** [comment]
@czechboy0 just tested it on our server and it's up and running fine. I verified that yes our workspace is using the xcscmblueprint (our project started in Xcode 7 beta) and never did have the .xccheckout file.

Thanks for the help!

**Comment by czechboy0** [comment]
Thanks @concertman, this is great to know in case other people are having the same issue.

**Comment by grantjk** [comment]
@czechboy0 Getting this same issue on 0.6. 

This project is an older project (pre Xcode7), but currently has a `xcscmblueprint` file in the `.workspace/xcshareddata/`.  I've created a bot manually that runs fine, but can't get past adding the workspace file in the buildasaur creation workflow

**Comment by czechboy0** [comment]
You're saying it has a blueprint file but Buildasaur isn't finding it? That's a bug, can you please create a new issue with all the details? Thanks!
