### ISSUE TITLE
Can you put bots or at least triggers under source control?

### ISSUE THREAD

**Issue by alimoeeny** [czechboy0/Buildasaur#145]
I think it is reasonable to share triggers (or even bots?) under source control and / or share them with team members. Specially if you have a people in different locations with their own network ...

**Comment by czechboy0** [comment]
Yes, great idea, this is actually something I've been considering for a while. I built a Ruby tool [xcskarel](https://github.com/czechboy0/xcskarel) which can actually [dump Bot config](https://github.com/czechboy0/xcskarel#manage-bot-configurations-in-your-git-repo) into a file (designed for this purpose). 

Let me know what exact workflow would be appropriate for you, there are many ways we could go about this.

**Comment by alimoeeny** [comment]
Thanks @czechboy0 , greatly appreciate your swift :) response.
I guess this overlaps with https://github.com/czechboy0/Buildasaur/issues/1
This is how I imagine it may work:
I create a bot and I want to share it with the rest of the team so that they can run their local bots, experiment with it, and when we change it we want to be able to keep track of changes and review the changes ....
I have experience with TravisCI and drone.io and similar CI systems, but very new to XCServer and Buildasuar (awesome name by the way, I pronounce it buildozer btw). 
let me look into your xcskarel to see how it works first.

**Comment by czechboy0** [comment]
Thanks @alimoeeny, that sounds great. Buildasaur saves its preferences to `~/Library/Application Support/Buildasaur` - would you want to add those into source control?

**Comment by alimoeeny** [comment]
Dude, you save my server password and my ssh passpharse and github token in plain text in `ServerConfig.json` and `Projects.json` . This is totally unacceptable. 
Can we do keychain?
Do you want me to send a PR for this? 

And yes, I think Having Build templates under source control would be enough. Thanks.

**Comment by czechboy0** [comment]
There is a ticket for this already: #137. Feel free to contribute if you really need it ASAP :) (just mark it in the ticket if you do, @Brett-Best was planning on implementing that, so let's make sure you guys don't duplicate your work).

**Comment by alimoeeny** [comment]
Thanks, I'll wait for @Brett-Best

**Comment by czechboy0** [comment]
Cool :+1:

**Comment by Brett-Best** [comment]
@alimoeeny I am hoping to have this done in the next week or so, feel free to submit a PR before that time though.
