### ISSUE TITLE
nothing happens when clicking save button on Build Template Settings sheet

### ISSUE THREAD

**Issue by mikewoodworth** [czechboy0/Buildasaur#157]
Cancel cancels the sheet, - deletes the template, Save seems to do nothing (no errors in console)

**Comment by mikewoodworth** [comment]
On further examination, it looks like this error may be related (el cap, server, xcode 7.0.1)

10/6/15 10:36:10.897 AM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.pid.xcodebuild.3782) Path not allowed in target domain: type = pid, path = /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/XPCServices/com.apple.lldb.launcherRootXPCService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = (unknown)

**Comment by czechboy0** [comment]
Thanks, @mikewoodworth, I'll take a look at it. I'm actually in the process (#138) of completely redoing the UI, so I'll make sure build template saving is working.

Just FYI, I just downloaded the latest release of [Buildasaur 0.5.0](https://github.com/czechboy0/Buildasaur/releases/tag/v0.5.0) and everything seems to work fine (I was able to create a Build Template and save it). I'm on El Cap. Can you please try to restart Builda and try again?

**Comment by mikewoodworth** [comment]
Still nothing... If I leave any of the fields at the top blank I get alerts. However I have everything above triggers filled in. The only blank section on the sheet is Build,Test. We are building a mac app, and there are no options in that dropdown.

**Comment by czechboy0** [comment]
Oooooh, yeah that's a sort of a bug of mine. It needs to know what platform the scheme is building for (because even when you're testing on a Mac, you'll see your Mac in the testing devices), but it doesn't reload it on start.

Towards the top, can you click on the scheme-selection popup, choose a **different** scheme and then select your original one again? This will kick in the reload of the devices and should hopefully fix this.

Please let me know if that was it!

**Comment by mikewoodworth** [comment]
the built,test dropdown is still empty after toggling (we only have one scheme - thought it seems to show up twice in the popup)

**Comment by czechboy0** [comment]
Hmm, I know that's annoying, but could you just mark another scheme as shared in Xcode so that it will show up in Buildasaur? Reselecting the same scheme doesn't reload it AFAIR, it needs to be a different scheme to kick in (sorry, this will be fixed in the next version).

**Comment by mikewoodworth** [comment]
still not seeing anything in the drop down (with 2 schemes), what should I be seeing there?

**Comment by czechboy0** [comment]
<img width="770" alt="screenshot 2015-10-06 19 35 58" src="https://cloud.githubusercontent.com/assets/2182121/10318462/83b1ee2c-6c61-11e5-8848-a44f82d0331e.png">

Something like this, I have one Mac duplicated (no idea why Xcode Server duplicates them).

**Comment by mikewoodworth** [comment]
so a quick look at the code. it appears that is being parse via xcodebuild -showBuildSettings when i run that here on the selected scheme i get a ton of things including:

```
PLATFORM_DISPLAY_NAME = OS X
PLATFORM_NAME = macosx
PLATFORM_PREFERRED_ARCH = x86_64
PLATFORM_PRODUCT_BUILD_VERSION = 7A1001
```

however the dropdown and the tableview are emtpy

**Comment by czechboy0** [comment]
Can you please try to clone Buildasaur and run it locally with the debugger attached and try running the script [here](https://github.com/czechboy0/Buildasaur/blob/75484a6179dfcf1f57b292d31d0e30f83a240307/BuildaKit/XcodeDeviceParser.swift#L58) in terminal, to see what you get back? That should give us a good idea of what's wrong. `xcodebuild -showBuildSettings` is just the start of the script, it's important that you run the whole thing. Thanks so much :+1:

**Comment by mikewoodworth** [comment]
so building from master seems to work fine. I noticed that code was updated 5 days ago, and 0.5.0 was posted 7 days ago... maybe this last fix solved the issue?

**Comment by czechboy0** [comment]
Maybe, try downloading 0.5.0 from the releases section here on GitHub and try that? Glad to hear that it's working though. Actually might have had something to do with #149.

Can you test and confirm for me that 0.5.0 is working please? So that I can close this ticket. Thanks a ton for reporting and providing more info, feedback like this is extremely important to me :)

**Comment by mikewoodworth** [comment]
0.5.0 from github (https://github.com/czechboy0/Buildasaur/releases/tag/v0.5.0) was what the bug was reported against.

**Comment by mikewoodworth** [comment]
to confirm, i just checked out this tag and the bug returned.

**Comment by czechboy0** [comment]
Right, sorry for being confusing. The PR I referenced is merged in master but not yet released. Which would point to that being the culprit. 

Let me create a patch release just for you. :8ball:

**Comment by czechboy0** [comment]
Cool, here it is: https://github.com/czechboy0/Buildasaur/releases/tag/v0.5.1 (downloadable the `.app` is below the release notes).

Please try it out and let me know if all is well, cheers. :+1:

**Comment by mikewoodworth** [comment]
this build is working great, thanks!
