### ISSUE TITLE
Blueprint file fails to validate

### ISSUE THREAD

**Issue by grantjk** [czechboy0/Buildasaur#172]
Similar to #140, I'm running into an issue where Buildasaur 0.6 fails to validate the blueprint file. I've confirmed that a blueprint file exists in the `.xcworkspace/xcshareddata` directory. I've also added the old `xccheckout` file as well.

The only thing that's different in this project that I can tell from the other projects I have is that there are two repos listed in the blueprint and the checkout file. I don't know why, and I don't know how to tell Xcode to ignore the irrelevant one. (if you have any tips, that would be great).

**Comment by Brett-Best** [comment]
Hello @grantjk are you using two remotes?

**Comment by grantjk** [comment]
Not according to `.git/config`. Not sure why Xcode things there's 2

**Comment by Brett-Best** [comment]
Hmmm can you post the blueprint? If you view the remotes in Xcode does it display two of them?

**Comment by czechboy0** [comment]
@grantjk This shouldn't be a problem, because the way Buildasaur parses the files is that it only picks the primary remote anyway. How does it fail? When adding the project does Buildasaur reject it?

**Comment by grantjk** [comment]
It fails [here](https://github.com/czechboy0/Buildasaur/blob/1340b87ecf3a489d955094414942a077cb119b43/BuildaKit/XcodeProjectParser.swift#L94) when I try to add the workspace file

**Comment by grantjk** [comment]
I created a bot through Xcoce already and it runs fine

**Comment by czechboy0** [comment]
One question - can you make sure that the blueprint/checkout files are in the **workspace**, if you're adding the workspace to Buildasaur, or in the **project** if you're adding the project? It only looks inside the file you give it: project vs workspace. That might be the reason why you have the required files, just in the other project/workspace file.

**Comment by grantjk** [comment]
Definitely in the workspace:

```
~/path-to-proj/ProjectName.xcworkspace/xcshareddata$ lsa
total 24
drwxr-xr-x  5 twg  staff   170B 14 Oct 08:43 .
drwxr-xr-x  5 twg  staff   170B 13 Oct 22:08 ..
-rw-r--r--  1 twg  staff   1.9K 14 Oct 08:43 ProjectName.xccheckout
-rw-r--r--  1 twg  staff   1.1K 13 Oct 22:42 ProjectName.xcscmblueprint
-rw-r--r--  1 twg  staff   264B 13 Oct 22:03 WorkspaceSettings.xcsettings
```

Here's the (obfuscated) blueprint file:

```
{
  "DVTSourceControlWorkspaceBlueprintPrimaryRemoteRepositoryKey" : "token",
  "DVTSourceControlWorkspaceBlueprintWorkingCopyRepositoryLocationsKey" : {
  },
  "DVTSourceControlWorkspaceBlueprintWorkingCopyStatesKey" : {
    "token" : 0,
  },
  "DVTSourceControlWorkspaceBlueprintIdentifierKey" : "identifier",
  "DVTSourceControlWorkspaceBlueprintWorkingCopyPathsKey" : {
    "token" : "repo-name"
  },
  "DVTSourceControlWorkspaceBlueprintNameKey" : "ProjectName",
  "DVTSourceControlWorkspaceBlueprintVersion" : 204,
  "DVTSourceControlWorkspaceBlueprintRelativePathToProjectKey" : "ProjectName.xcworkspace",
  "DVTSourceControlWorkspaceBlueprintRemoteRepositoriesKey" : [
    {
      "DVTSourceControlWorkspaceBlueprintRemoteRepositoryURLKey" : "ssh:\/\/github.com\/repo",
      "DVTSourceControlWorkspaceBlueprintRemoteRepositorySystemKey" : "com.apple.dt.Xcode.sourcecontrol.Git",
      "DVTSourceControlWorkspaceBlueprintRemoteRepositoryIdentifierKey" : "identifier"
    }
  ]
}
```

**Comment by czechboy0** [comment]
Hmm if you have Buildasaur running in the debugger, please try to see exactly what is failing, it might be actually failing to parse the file (but it's finding it).

For one thing, I don't think `DVTSourceControlWorkspaceBlueprintRemoteRepositoryURLKey` should start with `ssh`. Buildasaur's SSH URL is `github.com:czechboy0/Buildasaur.git`, for instance.

**Comment by grantjk** [comment]
@czechboy0 That was it. Not sure why Xcode would have generated the url that way... 

:shrug:

**Comment by czechboy0** [comment]
So it works? :+1:

**Comment by grantjk** [comment]
Yup. Works now. The error was parsing that url: [here](https://github.com/czechboy0/Buildasaur/blob/master/BuildaKit/WorkspaceMetadata.swift#L88)

Again, not sure why Xcode things that's the url...

**Comment by czechboy0** [comment]
Yeah I've never seen that either. Well, glad it works! (Make sure to commit the blueprint in your repo if you haven't already.)
