### ISSUE TITLE
Add Buildasaur to homebrew cask

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#189]
It would be really nice to have Buildasaur in [cask](https://github.com/caskroom/homebrew-cask) so it can be easily updated from command line since there are so frequent releases! (which is a good thing :smiley:)

**Comment by czechboy0** [comment]
Great idea! Can you link to a guide or something? I've never used cask myself.

**Comment by joelekstrom** [comment]
I think it should be pretty well described here:

https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by czechboy0** [comment]
https://github.com/caskroom/homebrew-cask/pull/14662

**Comment by czechboy0** [comment]
Done: https://github.com/caskroom/homebrew-cask/commit/241b722623c48535527e2d72d3b330b7a8515004

Can someone try to install Buildasaur with cask to confirm it's working, please?

**Comment by joelekstrom** [comment]
Awesome! I need to upgrade Buildasaur today so this is perfect. I will try it!

**Comment by joelekstrom** [comment]
Works perfectly. :smile: 

Should be in the readme!

**Comment by czechboy0** [comment]
#191 :)
