### ISSUE TITLE
Add pushing to Cask into the Fastfile release lane

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/Buildasaur#191]
See #189 for details.
- [ ] add to fastfile
- [ ] add Cask to readme as recommended installation

**Comment by joelekstrom** [comment]
:+1:

**Comment by czechboy0** [comment]
Does anyone want to take over this issue? I tried quickly playing with Cask, but didn't love how devs upload new versions, so I didn't finish it.

Basically we need to add a step to the Fastfile which automatically uploads a new spec to the Cask repo based on the other information in the context. Look at the `release` lane.

**Comment by czechboy0** [comment]
Duplicate of #229
