### ISSUE TITLE
Put logs into a separate folder

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/Buildasaur#202]
Enhancement of #142, instead of keeping log files at the root of the Application Support folder, let's put them into a nested folder `Logs` to keep the tree hierarchy clean. This is more important now that logs are being split into multiple files.

**Comment by czechboy0** [comment]
@accatyyc No pressure, but do you want to do this one? It's ok if not, just offering an easy task that continues on top of what you worked on :)

**Comment by joelekstrom** [comment]
I can do it, I'm a bit busy for a few days/the coming weeks so maybe not right now if you want it earlier, but I'll add it to my todos.

**Comment by czechboy0** [comment]
No rush 👍

**Comment by czechboy0** [comment]
No worries, I'll do this as part of migration I'm working on.

**Comment by joelekstrom** [comment]
:+1:

**Comment by czechboy0** [comment]
Fixed in #209, will appear in v0.8.
