### ISSUE TITLE
Create a Sparkle xml feed update fastlane action

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/Buildasaur#228]
Based on https://github.com/CocoaPods/CocoaPods-app/blob/master/Rakefile#L1069

**Comment by KrauseFx** [comment]
You mean a new fastlane lane for Buildasaur to release a new version of Buildasaur for Sparkle?

**Comment by czechboy0** [comment]
No, a fastlane action that updates the Sparkle xml feed by adding the new version.

**Comment by czechboy0** [comment]
See the link above for an example of how CocoaPods App does it.
