### ISSUE TITLE
Buildasaur doesn't extract repo name from GitHub url that does not end in ".git"

### ISSUE THREAD

**Issue by lindsaylandry** [czechboy0/Buildasaur#244]
Sometimes github strings do not have ".git" attached to the end.
If this happens, Buildasaur will give an error message on the SSH Keys setup page. The message says: "Invalid repo name."

Example github string (without ".git"):
 git@github.com:organization/repo_name 

I have a fix that will address both kinds of strings to extract the repo name (basically creates a Range object that starts and ends at the end of the string if it cannot find ".git")
[Project.swift.zip](https://github.com/czechboy0/Buildasaur/files/153485/Project.swift.zip)

Buildasaur/BuildaKit/Project.swift

Replace the following lines:

`- if let githubRange = stringUrl.rangeOfString(serviceUrl, options: NSStringCompareOptions(), range: nil, locale: nil),`
`- let dotGitRange = stringUrl.rangeOfString(".git", options: NSStringCompareOptions.BackwardsSearch, range: nil, locale: nil) {`

`+ let dotGitRange = stringUrl.rangeOfString(".git", options: NSStringCompareOptions.BackwardsSearch, range: nil, locale: nil) ?? Range(start: stringUrl.endIndex, end: stringUrl.endIndex)`
`+ if let githubRange = stringUrl.rangeOfString(serviceUrl, options: NSStringCompareOptions(), range: nil, locale: nil){`

**Comment by czechboy0** [comment]
Hi @lindsaylandry,

thanks for reporting this. I'm however wondering whether a git remote URL not ending with `.git` is a valid git URL? Do you have an example of a GitHub project that has a git URL not ending with .git? Because this is new to me so I need to understand the issue first :)

**Comment by czechboy0** [comment]
Ok, TIL that you don't need the `.git` suffix.

Thanks so much for reporting this! Could you fork this repo and send a Pull Request with the fix above, so that I can just merge it? If that's a problem, I can apply the fix manually.

**Comment by lindsaylandry** [comment]
Any git repo can be cloned in this way.
For example, your own Buildasaur repo can be cloned like this:

git clone git@github.com:czechboy0/Buildasaur

if you leave the .git extension out, it still works.
I have created a forked branch already, but when I tried to push onto master, I didn't have permission. I can submit a PR if you give me temporary permissions :)

**Comment by czechboy0** [comment]
You can just create a fork of the repository if you click on the fork button top right, clone and apply the fix there, and then create a cross-fork Pull Request :) If you haven't worked with forks before, here's some [info](https://help.github.com/articles/about-forks/) from github.

**Comment by lindsaylandry** [comment]
oh thanks very much, looks like I learned something today as well.

**Comment by czechboy0** [comment]
Fixed by #246.
