### ISSUE TITLE
Internal Server Error (xcssecurity): could not read password from keychain

### ISSUE THREAD

**Issue by bclark** [czechboy0/Buildasaur#245]
My repo is hosted on Stash, so when choosing a new project that has an existing bot I got the .xcscmblueprint issue. 

I attempted to have it manually fixed, by using the curl method.  However when I pull down the initial data to get the BOT_ID everything goes fine.

Once I attempt to then use the BOT_ID I get the following response:

`{"status":500,"message":"[XCSSecurity - findItem] error: [XCSSecurity - launchTool] Internal Server Error (xcssecurity): could not read password from keychain: The specified item could not be found in the keychain."}`

**Comment by czechboy0** [comment]
Hi @bclark,

I've never seen that issue. You mention having the blueprint in your repo - could you try the following so that we can better pinpoint the issue?

Buildasaur doesn't need those files anymore, it tries to detect the origin from the repo the project is in - so can you please try to remove the blueprint file and remove/re-add your project to Buildasaur? Then please try to enable the syncing again and see what you get (also deleting those bots might help to get a clean state).

Also, technically Buildasaur only supports BitBucket's Cloud version and not yet self-hosted Stash. Are you running a self-hosted or a cloud-hosted version?

**Comment by bclark** [comment]
I actually don't have the blueprint file. I checked and made sure it was not in the repo and I still get this:

>  Cannot find the Checkout/Blueprint file and failed to parse repository metadata directly. Please create an issue on GitHub with anonymized information about your repository. (Error Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH). Cannot find the Checkout/Blueprint file and failed to parse repository metadata directly. Please create an issue on GitHub with anonymized information about your repository. (Error Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH).

I am using cloud hosted Stash through Atlasssian.

**Comment by czechboy0** [comment]
Hmm, something went wrong then. Are you using the latest version of Buildasaur (1.0.0-b2)? Are you compiling from source or running the downloaded release? I'll try to reproduce it locally if you provide me with more info :)

**Comment by bclark** [comment]
I am using the latest download release. Choosing the latest develop branch locally, with origin being cloud hosted Stash. I also have Carthage in my project, which helps build another project as a framework .

**Comment by czechboy0** [comment]
:( It seems like the git info parsing failed. Can you share what your git remote URL is? Is it checked out over SSH? (HTTPS doesn't work yet unfortunately)

**Comment by bclark** [comment]
Unfortunately I can't share the URL. I may try and re-check it out.

**Comment by czechboy0** [comment]
Yeah I figured. Okay try to check it out again with SSH and please let me know if that fixed the issue, thanks

**Comment by bclark** [comment]
Doesn't look like it helped. I still get 

> Cannot find the Checkout/Blueprint file and failed to parse repository metadata directly.

**Comment by czechboy0** [comment]
Weird. Can you post the git URL your remote has? Feel free to replace any confidential info, so `git@github.com/NAME/PROJ.git` is just fine.

If that doesn't work and you definitely checked out over SSH, you might need to clone Buildasaur and run it locally to see where things go wrong. Without getting my hands on your project I can't do much more, sorry :(

**Comment by bclark** [comment]
ssh://git@git.company.com:7999/ma/project-ios.git

I understand that it's tough to debug, but I appreciate the help.

**Comment by czechboy0** [comment]
Ah, is that a GitHub Enterprise or self hosted Bitbucket  server? Unfortunately self hosted servers aren't supported by Buildasaur yet. 

You can track tickets #99 and #238

**Comment by czechboy0** [comment]
Only regular GitHub and BitBucket projects (cloud hosted) are supported at the moment.

**Comment by czechboy0** [comment]
I'll close this for now, because I'm assuming you're not using GitHub/BitBucket-hosted repo, which are the only ones supported. See ticket numbers above for self-hosted GitHub and BitBucket. But I'll appreciate any info around your setup/scenario that you wish Buildasaur supported.

**Comment by rcaileff** [comment]
I can confirm that the error message bclark saw is the one you get when you try to use an enterprise github server.
