### ISSUE TITLE
Analyzer warning counts in commits and email text

### ISSUE THREAD

**Issue by eric-chamberlain-intel** [czechboy0/Buildasaur#253]
I haven't looked into the code, are the analyzer warning counts available for use in the commit and email text?  We'd like developers to be able to see analyzer warning counts along with build warning counts.

**Comment by czechboy0** [comment]
You mean in the comments posted by Buildasaur after an integration finishes? Like [this one](https://github.com/czechboy0/Buildasaur/pull/224#issuecomment-176415683)?

If so then yes, all the following counts are included if present:
- warnings
- analyzer warnings
- error
- test failure
- code coverage percentage

You can see how it works [here](https://github.com/czechboy0/Buildasaur/blob/master/BuildaKit/SummaryBuilder.swift#L128).

Is this what you meant? :blush:

**Comment by eric-chamberlain-intel** [comment]
Yes, does it display all that by default?  Our implementation is not displaying analyzer warnings.

We are using the pre-compiled build, if that helps.

**Comment by czechboy0** [comment]
Interesting. In those integrations, are you seeing any warnings being mentioned in the comment? I now see that [this](https://github.com/czechboy0/Buildasaur/blob/master/BuildaKit/SummaryBuilder.swift#L35) code will in fact **not** properly add analyzer warnings if the integration finished with status `warnings` or `passed`.

Could you please try to call this on your Xcode Server locally: 

```
curl -k https://127.0.0.1:20343/api/bots
```

where 127.0.0.1 is the address of the server, so replace it with the proper IP if you're calling it on a local network from a different machine. This will give you a JSON representation of all bots. Please find the one that you're seeing the issue on and find its `_id`. Then run

```
curl -k https://127.0.0.1:20343/api/bots/BOT_ID/integrations
```

and assuming the integration that should be showing analyzer warnings is the last one, it'll be the first in the list. There you should see with which status it ended (`succeeded`, `warnings` or `analyzerWarnings`) and what its `buildSummary` was. If you can find those two and let me know, I'll understand how to fix it if there's really a bug.

Thanks!

**Comment by eric-chamberlain-intel** [comment]
Yes, we have compiler warnings present in the comment.

**Comment by eric-chamberlain-intel** [comment]
Here is the relevant curl output:

...
"buildResultSummary":{"analyzerWarningCount":24,"testFailureCount":0,"testsChange":0,"errorCount":0,"testsCount":60,"testFailureChange":0,"warningChange":0,"regressedPerfTestCount":0,"warningCount":5,"errorChange":0,"improvedPerfTestCount":0,"analyzerWarningChange":0,"codeCoveragePercentage":7,"codeCoveragePercentageDelta":0},"result":"warnings"
...

We are running Xcode 7.3.

**Comment by czechboy0** [comment]
Thanks! Yeah that's what I thought. I'll fix the bug now, will let you know once a new version with this issue fixed is out. If you're running 1.0-beta2, you'll be able to update directly from Buildasaur.

**Comment by czechboy0** [comment]
Done, the release is here: https://github.com/czechboy0/Buildasaur/releases/tag/v1.0.0-b3
And you can just update directly from Buildasaur.

Let me know that it works as you expect now, please! :blush:

**Comment by czechboy0** [comment]
Cool, so @eric-chamberlain-intel - the bug is fixed by #254. I'll do a new release 1.0.0-beta3 now so you should see Buildasaur ask you to update soon. If you want to do it manually just click on the little refresh icon in the Buildasaur dashboard.

**Comment by eric-chamberlain-intel** [comment]
It works as expected.  Thank you for the quick turnaround.

**Comment by czechboy0** [comment]
:+1:
