### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by paul-delange** [czechboy0/Buildasaur#256]
Great work by the way. Your documentation has been really helpful - even after Apple released their official API. 

Do you think it might be possible to hijack a bot and get it to build and test an Android app (Gradle based build script)? I think this might require modifying some of the javascript files in the Xcode xcs folder. Any ideas? The goal is to have iOS & Android builds running and reporting on the same monitor (and every developer loves the Apple big screen UI! )

**Comment by czechboy0** [comment]
Hi @paul-delange, thanks!

I'm afraid it's not possible - AFAIK the actual building is done with Objc code that's shipped as part of Xcode. The javascript files only control how the API server works, but the building is done with native tools.

Feel free to give it a try and let me know if you find anything, but I won't be of much help here, sorry. :blush:

**Comment by gruberjuliannama** [comment]
Nethne memorenyme? nicsewerne tenymeryne.....?

**Comment by gruberjuliannama** [comment]
Nethne memorenyme? nicsewerne tenymeryne.....?

2016-04-04 9:32 GMT+02:00 Honza Dvorsky <notifications@github.com>:

**Comment by czechboy0** [comment]
@gruberjuliannama Apologies, I only speak English and Czech. Do you have a question regarding this issue? :blush:

**Comment by gruberjuliannama** [comment]
English-Italian writing?,, It was ??

I do not know your specific and variable? "+ ....? how much of the program
?? !! Quantity is building thanks ???

2016-04-04 12:02 GMT+02:00 Honza Dvorsky <notifications@github.com>:

**Comment by gruberjuliannama** [comment]
much of the program,, !! Quantity?? which is building ??? ,, thanks !!

2016-04-04 12:08 GMT+02:00 Julian Gruber <julaner007@gmail.com>:

**Comment by czechboy0** [comment]
Sorry, I'm not sure I understand. I'm going to delete these comments for now, feel free to create a new issue if you have any specific question :blush:

**Comment by eric-chamberlain-intel** [comment]
@paul-delange The process would be no different than getting Xcode to build an Android project on the desktop.  If you had an empty project that fired off Android build scripts, some functionality might work.

**Comment by czechboy0** [comment]
Ah I see. Yeah you could hack it like that. Do you want to try such project with Buildasaur?

**Comment by czechboy0** [comment]
I definitely won't be able to investigate this myself, but if you do find a way to get it work that's not too intrusive to the main codebase, I'd love a PR!
