### ISSUE TITLE
Repository not found error

### ISSUE THREAD

**Issue by thalmicMark** [czechboy0/Buildasaur#257]
I'm attempting to setup Buildasaur on our build machines, but I continue to encounter the following error when I start the syncer:

```
UserInfo={NSLocalizedDescription=Unrecognized error: {
    code = "-1";
    domain = "com.apple.dt.SourceControlErrorDomain";
    message = "ERROR: Repository not found. (-20)";
    underlyingError = "ERROR: Repository not found. (-20)";
}
```

Here's the steps I followed to set up the syncer:
- Clone the repository locally using our build machine's GitHub account.
- In Buildasaur, I create a new syncer and select the correct Xcode Server (and provide login credentials).
- I select the correct `.xcodeproj`.
- I select the ssh keys that we use for our build machine's GitHub account.
- I click log in, and sign in with our build machine's GitHub credentials.
- I select a build template.

When I then click start, I continually get the above error. How could Buildasaur not have access to the repo if every step in the setup passed verification?

**Comment by czechboy0** [comment]
That's very strange indeed. This seems like an error in Xcode Server, which Buildasaur is receiving from it. It's possible that there's a bug but I won't be able to track it down without more details. 

Is your repo public or private?

**Comment by thalmicMark** [comment]
My repo is private. Any other details I can provide?

**Comment by czechboy0** [comment]
Hmm can you try to create a bot manually from Xcode on your build server? And see if that works?

**Comment by thalmicMark** [comment]
I am able to create bots manually using Xcode on my development machine and have them run successfully. I am also able to do the same in Xcode on my build machine (using the same ssh keys I mentioned in my first post for authentication). Do you want me to send you the Buildasaur logs?

**Comment by czechboy0** [comment]
Sure my username at gmail.

**Comment by czechboy0** [comment]
Please reopen this issue if you're still having this issue, thanks 😊

**Comment by danielgalasko** [comment]
We seeing the same issue here as well. Also private setup and we can run bots etc

Its weird because it only happens when we try from a mac mini, setting up locally it works.

Ideas?
