### ISSUE TITLE
Use Buildasaur with a private gitlab instance

### ISSUE THREAD

**Issue by MartinDelille** [czechboy0/Buildasaur#262]
Hi,

I'd like to use Buildasaur with my private gitlab instance. I'll be happy to share my patch, but I wondered if  you had planed to implement this and how?

**Comment by czechboy0** [comment]
Sure, I've had people asking for it (#109), so a PR would be very welcome! 😊

**Comment by czechboy0** [comment]
If you do make progress, please comment in the original issue #109, thanks!
