### ISSUE TITLE
Error Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH

### ISSUE THREAD

**Issue by nestorlafon** [czechboy0/Buildasaur#263]
I got the following error adding a repo:

> Couldn't add Xcode project at path file:///Users/mxbot/myproject/myproject.xcworkspace, error: Cannot find the Checkout/Blueprint file and failed to parse repository metadata directly. Please create an issue on GitHub with anonymized information about your repository. (Error Disallowed checkout type, the project must be checked out over one of the supported schemes: SSH).

Although the repo was clone using SSH I followed the workaround steps creating the blueprint file but I still get the same error.

Is it possible to get more detail about what is producing the error?

The blueprint file added looks like (anonymised):

```
{
   "DVTSourceControlWorkspaceBlueprintPrimaryRemoteRepositoryKey":"FF6F1F3CB80AF41215B17903BEEF908A02B36D30",
   "DVTSourceControlWorkspaceBlueprintWorkingCopyRepositoryLocationsKey":{

   },
   "DVTSourceControlWorkspaceBlueprintWorkingCopyStatesKey":{
      "FF6F1F3CB80AF41215B17903BEEF908A02B36D30":0
   },
   "DVTSourceControlWorkspaceBlueprintIdentifierKey":"A07FFC0C-8CE7-4944-8C3F-4CADC5C97122",
   "DVTSourceControlWorkspaceBlueprintWorkingCopyPathsKey":{
      "FF6F1F3CB80AF41215B17903BEEF908A02B36D30":"myproject/"
   },
   "DVTSourceControlWorkspaceBlueprintNameKey":"myproject"
   "DVTSourceControlWorkspaceBlueprintVersion":204,
   "DVTSourceControlWorkspaceBlueprintRelativePathToProjectKey":"myproject.xcworkspace",
   "DVTSourceControlWorkspaceBlueprintRemoteRepositoriesKey":[
      {
         "DVTSourceControlWorkspaceBlueprintRemoteRepositoryURLKey":"git@github.mycompany.com:myorg/myproject.git",
         "DVTSourceControlWorkspaceBlueprintRemoteRepositorySystemKey":"com.apple.dt.Xcode.sourcecontrol.Git",
         "DVTSourceControlWorkspaceBlueprintRemoteRepositoryIdentifierKey":"FF6F1F3CB80AF41215B17903BEEF908A02B36D30"
      }
   ]
}
```

Thanks for your work!

**Comment by czechboy0** [comment]
Hi @nextorlg, 

first of all, great issue report! That's all I need to be helpful here. 
I can see from your blueprint that your repo URL is `git@github.mycompany.com:myorg/myproject.git`, which implies you're using GitHub Enterprise, instead of GitHub.com, correct?

If so, technically Buildasaur doesn't yet support Github Enterprise servers, but there are a couple of people working on it (and have their forks), see this issue with links: #99. There's even a WIP pull request: #251.

Hope this helps. As I don't have an Enterprise server myself, I can't get the support in myself, so I'm relying on contributors. It might be worth to try to chat to them directly.

**Comment by czechboy0** [comment]
Possibly related to #259.

**Comment by nestorlafon** [comment]
Yup looks related to the github enterprise instance. Our setup is not standard, I will check the issues as PRs you referenced and see if I can be of some help

**Comment by czechboy0** [comment]
As we don't technically yet support GitHub Enterprise yet, I'll close this. If you're using a fork of Buildasuar, it's probably best to open a ticket in the fork's issues section and later try to ask them to PR the improved version into main Buildasaur. Unfortunately I cannot help with forked code as I don't know what's been changed.
