### ISSUE TITLE
Cannot depend on xcxcmblueprint file to be accurate

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#264]
Given that we have a proper xcscmblueprint file for a project.
This file does not seem to be updated or maintained, or recreated or verified at any time.

1) Do we have a way to re-create it on demand?

2) Do we have to edit this file by hand if we clone a repository and change the origin?

3) What creates, manages or updates this file?

In question #2, I am working on a cloned copy of a live project, but pushed to another repository.
The .xcscmblueprint file contains the source repository of the original repository and not the new repository.

Shouldn't we recurse back to the most recent .git directory in the current tree branch and use the repository location specified in the 'remote origin' instead of blindly using the value stored in the xcscmblueprint file?

Ideally get the result of `git remote -v`

**Comment by czechboy0** [comment]
You can just delete the blueprint file and Buildasaur will figure out all these things on its own. The blueprint and checkout files are more of a legacy option.

**Comment by reststop** [comment]
I think in the fork I'm working on, it won't let me create a project or syncer without an xcscmblueprint file.
(Or I couldn't get past the screen that relied on finding it: linked to workaround #165)

**Comment by czechboy0** [comment]
That's strange, is it checked out over SSH?

**Comment by reststop** [comment]
Ok, so at some point, I can delete the manufactured .xcscmblueprint file.  I will try it.

Yes. over SSH.

**Comment by reststop** [comment]
Ok, that is working now without the .xcscmblueprint file.  (Good I can delete it from the repository)

Possibly the former issue was showing up before I patched the method which returned the sshURL to detect the correct clone/url entry.  (It was always returning the 0th entry which on our Stash was returning the HTTP URL.)

I no longer see the error/workaround alert message, and it allows me to select the project just fine and it finds the correct repository.

Thanks.  I guess we can close this issue.
