### ISSUE TITLE
Wrong repo found on forked/cloned projects

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#265]
Similar to the issue I opened on unable to depend on xcscmblueprint file.
Someone intricately knowledgeable about this matter would catch it, but a normal user would not.

If you clone a forked project, (and probably even copy a project without cloning), the existing artifacts in the project are used to determine the repo location, and this is inherently unreliable.

Case in point.  I forked a fork of Buildasaur (github:gchiong/Buildasaur) into github:reststop/Buildasaur and then mirrored that repository into our Stash server (stash.mycompany.com/projects/PROJECT/repos/buildasaur) so I could debug the pull request API on Stash.

When I selected the project on my local system, the result location for the repo is:
git@github.com:czechboy0/Buildasaur

This is obviously incorrect.

This should really get the repository info from the git structure.
e.g. base/.git/config for the current repo, or at least some more reliable source.

**Comment by czechboy0** [comment]
If you make sure to delete the blueprint and checkout files and let Buildasaur detect the repo itself, it will run `git remote -v` and take the first remote with a `(fetch)` parameter, see code [here](https://github.com/czechboy0/Buildasaur/blob/master/BuildaKit/GitRepoMetadataParser.swift#L24).

So when you fork and clone that fork, everything should work well (but again, you need to make sure to _not_ have any blueprint or checkout file in the project/workspace).

**Comment by reststop** [comment]
Yes, I just tested that.

It appears to check the .xccheckout file first, then the xcscmblueprint file second.
Moving those (or deleting those) then it found the correct repository.

I suggest making a note of this in the documentation so people who clone others' projects will not end up checking for pull requests on the wrong repository. (I don't recall seeing anything in the setup docs)

**Comment by czechboy0** [comment]
Yeah that's a good point. Let's hope that they'll at least find this issue if they look for more info. Thanks for reporting this!

**Comment by reststop** [comment]
I was going to note that there may be more than one remote, but looking at the code link you provided, you do check for the one that says "origin".  You're good!

**Comment by czechboy0** [comment]
Yeah it's just a set of cascading heuristics.
