### ISSUE TITLE
Best place to print out contents of request/response?

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#267]
I've had no luck finding  convenient place to print out the contents of the POST or GET for the API calls so that I can verify that they match what I'm looking to send or receive.

All the places I see a json object, I'm unable to see the contents. I may just not be looking at the right places or using the right methods.
Is there a reasonably central place where I can add a Log.verbose() to examine the outgoing URL/body and incoming json -- both to the server, and to the repository?

**Comment by czechboy0** [comment]
There is, just not in Buildasaur, but in its dependency called BuildaUtils. Just add the log locally in your clone somewhere here: https://github.com/czechboy0/BuildaUtils/blob/master/Source/HTTPUtils.swift#L36

**Comment by reststop** [comment]
Ok, thanks.  I had looked in that vicinity and had breakpoints there while
debugging but was't seeing the actual URL visibly.  I'll poke around some
more and see what I must have nissed.
