### ISSUE TITLE
Support for cleaning up older integrations?

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#269]
Question:  Is there any support for cleaning out old integrations?

For example, setting a limit, either by date (how old), or by the number of current integrations available on disk, or clearing the cache for a particular bot.

Yes, this isn't specifically for Syncer/PR bots in general, since they are automatically created, and deleted.  Do we know if the Integration cache is deleted for an integration, or for the bot when it is deleted?

One of our projects is very large (on the order of nearly 2 GB in source and frameworks in git) and each IPA created (15 of them for every Integration) close to 250 MB each (8.75GB), and growing.  Currently I manually remove older integrations, via the server GUI or simply deleting the IntegrationAssets directories for older integrations (which leaves the integrations in the servers database).

This might not be germane to Buildasaur, and might be a separate project using the server SDK, but I thought you would one of the best people to ask if you know if any working projects, or projects in progress on this topic.

Thanks.

**Comment by czechboy0** [comment]
All that is in Xcode Server's responsibility, unfortunately Buildasaur can't affect that AFAIK.

**Comment by reststop** [comment]
Thanks.  I'll have to take a look deeper into a new project.  Actual space
can be done with some simple scripting, but cleaning up the DB is the hard
part.  I cannot believe that Apple didn't think to add that capability.
