### ISSUE TITLE
Support for SSH passphrases

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#27]
When generating SSH keys, you can optionally enter a passphrase. When setting up bots in Xcode, and setting credecentials -> Existing SSH keys, there is a field to enter this passphrase so Xcode can decrypt the keys.

There is no such field in Buildasaur, and when trying to use encrypted keys, buildasaur will say "Verified access, all is well" but all bots will fail to check out.

Suggested solution: Add a passphrase field and forward it to the Xcode bots if not left empty.

**Comment by czechboy0** [comment]
Great point, I completely forgot about this feature. It will require me looking into how to pass it in the Xcode Server API, but will be easy to add in the UI. 

Also, this uncovered another issue - the validation only checks the GitHub token, not the SSH keys. Do you know an easy way to verify SSH key access to a repo without checking it out?

**Comment by joelekstrom** [comment]
Check out `git ls-remote`, it will fail if there is no permission to access the repo. Not sure about how to supply it the SSH-keys though. I'll get back to you if I think of something!

**Comment by czechboy0** [comment]
Thanks, this is useful!

**Comment by joelekstrom** [comment]
Check out the top answer here http://stackoverflow.com/questions/4565700/specify-private-ssh-key-to-use-when-executing-shell-command-with-or-without-ruby.

I think it will solve your problem. It will invoke the SSH agent, add the keys temporary, and then you can execute `git ls-remote` from the SSH agent context. That way you should be able to verify the credentials without permanently changing the users SSH agent.

**Comment by czechboy0** [comment]
@accatyyc I tried the solution from stackoverflow, unfortunately that doesn't seem to force the use of the specify the use of those SSH keys, instead it seems to add that key. So if on your machine, where you already have access to a repo and you specify different keys for Builda, I can't verify that those new keys are wrong. I'll keep looking.

**Comment by czechboy0** [comment]
So I started looking into passphrase support, and I can't seem to find a way to provide the passphrase on the command line for `ssh` when validating the keys. Seems to require some tool called `sshpass`, but I can't require people to install this. That means that the first time when trying to validate (when saving the settings), a popup asking for the SSH passphrase would pop up (not terrible but annoying, if we want to add the passphrase as another field in the setup). Any ideas?

**Comment by czechboy0** [comment]
Actually, I found a much simpler way, which will make yesterday's work unnecessary (the git 2.3 hacking). I already had a hunch in #25, I'm using a hidden Xcode Server tool called `xcsbridge` which has blueprint validation (blueprints contain git credentials and verify they are correct). Making the changes now.

**Comment by czechboy0** [comment]
@accatyyc Okay, this is fixed. In the UI now you should see a textfield to put the SSH passphrase. Thanks for reporting this!
