### ISSUE TITLE
Repository maintenance not recognized

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#271]
Buildasaur works fine when a given response returns a maintenance window message, however the log is then littered with all manner of HTTP and CSS text.  I'm sure we don't want to parse the possible maintenance window messages, but it does happen and BUildasaur ought to recognize the problem and act accordingly instead of failing so verbosely before eventually recovering and resuming
 (maybe not in GitHub, but I have seen it on Bitbucket, and more than likely on any in-house servers: Bitbuket Server, GitHub Enterprise, GitLab, Stash.

If there is an API to check for availability, this would be a good thing to add.  (I don't know if any of the services have an API, or if the current HTTPS: request returns any kind of redirect, but I have seen in our "Builda.log" messages similar to the one below.  I've truncated it, but it can be lengthy.

[Builda.log.zip](https://github.com/czechboy0/Buildasaur/files/267193/Builda.log.zip)

<pre>
[INFO]: Sync starting at 2016-05-13 17:50:57 +0000
[ERROR]: Syncing encountered a problem. Error: Wrong body Optional(<html>
<body>
<center>
<img src="https://mycompany.com/images/maintenance.png" alt="" title="" /></a>

<p style="font-family:arial;font-size:20px;">
You have reached <strong>Stash</strong> during a maintenance window. We apologize for the inconvienence. Please try again later.
</p> 
...
</pre>

or

<pre>
[INFO]: Sync starting at 2016-05-13 18:04:57 +0000
[ERROR]: Syncing encountered a problem. Error: Wrong body Optional(

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE">
    <title>Atlassian Stash - Starting</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            background-color: #F0F0F0;
            color: #666666;
            text-align: center;
            margin-top: 90px;
            font-family: sans-serif;
            font-size: 18px;
            line-height: 1.3;
        }

...
                        <g class="rotating" fill="#205081">
                            <path d="M10.088,14.207c0.026,0,0.053-0.003,0.079-0.009c2.428-0.545,4.189-2.76,4.189-5.264               c0-0.55-0.083-1.094-0.244-1.615c-0.034-0.106-0.114-0.193-0.218-0.233c-0.102-0.041-0.218-0.031-0.315,0.024l-0.652,0.38               c-0.144,0.083-0.214,0.255-0.17,0.416c0.092,0.336,0.137,0.682,0.137,1.029c0,1.778-1.193,3.336-2.899,3.79               c-0.162,0.042-0.273,0.189-0.273,0.356v0.758c0,0.112,0.05,0.218,0.137,0.288C9.924,14.178,10.005,14.207,10.088,14.207z"/>

...
            background: url(data:image/svg
**Many Lines of base 64 data**
);

</pre>

</html>

**Comment by czechboy0** [comment]
Interesting, Buildasaur is stateless, so it'll try to ask the server for the data every 30 seconds (or however frequent your sync interval is). It does seem verbose, but it's an error, unexpected state, so I think logging it is the best thing to do.

I'd be fine if you file a PR that detects this case specifically for BitBucket servers and prints less, but I won't have time to do this myself.
