### ISSUE TITLE
Cancel integration not working

### ISSUE THREAD

**Issue by pavm035** [czechboy0/Buildasaur#272]
Hi,

I have tried cancelling integration through this swift code, but looks like request not completed successfully rather it throws following error

NOTE: But Post integration works fine

Optional(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x7fd8684d97a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://xxxx.server.com/api/integrations/BOT_ID/cancel, NSErrorFailingURLKey=https://xxxx.server.com/api/integrations/BOT_ID/cancel, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.})

Code:

server.cancelIntegration("BOT_ID") { (success, error) in
            print(error)
            print(success)
        }

Also i'm passing right credentials, Any help highly appreciated.

**Comment by czechboy0** [comment]
Hi @pavm035,
- are you using the code from master from this repo or a fork?
- have you managed to get Buildasaur working? If you're just using [XcodeServerSDK](https://github.com/czechboy0/XcodeServerSDK), that's its own project, so we could discuss this issue there if it's related to it
- what Xcode/Xcode Server version are you running?

These should help me better understand what we're dealing with here 😊 Thanks

**Comment by pavm035** [comment]
Hi @czechboy0 
Thanks for your quick response, 

**are you using the code from master from this repo or a fork?**
In fact i have added 'XcodeServerSDK' as pod dependency in sample project

**have you managed to get Buildasaur working? If you're just using XcodeServerSDK, that's its own project, so we could discuss this issue there if it's related to it**
Sure we can discuss in XcodeServerSDK project only.

**what Xcode/Xcode Server version are you running?**
Xcode 7.3, OSX Server version: 5.1

**Comment by czechboy0** [comment]
Cool, closing this and moving to https://github.com/czechboy0/XcodeServerSDK/issues/134
