### ISSUE TITLE
Error: Failed to post a status ... on commit

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#273]
Ok, error first seen while debugging Issue #261 

The problem seems intermittent, and when debugging the earlier issue, I saw it in passing, but was unable to make it happen on every request.  Letting the syncer run overnight or for long periods, I see this type of error several times a day, but have not recognized a pattern.

The (...,nil) in the title was an addition in my code (status) to see what status was attempted to be posted.  When I see the error, it is always nil.

<pre>
[ERROR]: Syncing encountered a problem. Error: Failed to post a status **nil** on commit 46a596181769e02277a19c2a09848d1b203fb7d0 of repo myproject/my-repo. Context: SyncPair: PR (407:k/1234-wheel) + Bot (β [my-repo] k/1234-wheel)
</pre>

Looking for suggestions on what might be causing the problem (including that the status it is posting happens to be nil)

A related question is:
**Is Buildasaur supposed to add any comments to the PR, for example with the results of the build?**

I do not see any comments created by Buildasaur on the actual PRs.  I do see the status info where I see "1 build", "1 build in progress", or "1 build failed", but no other info.  Clicking on the status does send me to Xcode to view the status.  **Is the status from the build supposed to be posted as a comment or not?**

Running 1.0.0-b2, code forked for Bitbucket Server.  Trying to identify if it is a Bitbucket server issue or not.  Since we don't have any github projects (I guess I could stage one), I don't have anything to compare against.

**Comment by reststop** [comment]
Slightly more info after fixing (status) to say (statusWithComment.status)
And dumping contents of Status dictionary:

<pre>
[VERBOSE]: BBEStatus: {
    description = "Build waiting in the queue...";
    key = Buildasaur;
    name = Buildasaur;
    state = INPROGRESS;
    url = "https://stlt.herokuapp.com/v1/xcs_deeplink/myserver.com/fb69145e64f3806cec314c66b5fcc66a/aae9ab4de88ee161ac51fd231005d975";
</pre>

[ERROR]: Syncing encountered a problem. Error: Failed to post a status **BuildaGitServer.BitBucketEnterpriseStatus** on commit ce6ca2571ebe0d8b59e667dc7dbaffa69ceb63a5 of repo

**Comment by reststop** [comment]
Seeing that it only happens on some status posting.... looking for a pattern.
Other statuses are posted fine:  e.g.  These did not hit the error breakpoint:

<pre>
[VERBOSE]: BBEStatus: {
    description = "Build waiting in the queue...";
    key = Buildasaur;
    name = Buildasaur;
    state = INPROGRESS;
    url = "https://stlt.herokuapp.com/v1/xcs_deeplink/myserver.com/aae9ab4de88ee161ac51fd231005ca35/aae9ab4de88ee161ac51fd231005f6f9";
}
[VERBOSE]: BBEStatus: {
    description = "Integration step: building...";
    key = Buildasaur;
    name = Buildasaur;
    state = INPROGRESS;
    url = "https://stlt.herokuapp.com/v1/xcs_deeplink/myserver.com/fb69145e64f3806cec314c66b5fcc66a/aae9ab4de88ee161ac51fd231005d975";
}
</pre>

**Comment by czechboy0** [comment]
Once again, @reststop, unfortunately this looks like all BitBucket Server code, which was written by someone else, so I'm afraid I can't help you here.
