### ISSUE TITLE
Question: Preference for adding a service

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#279]
Hi Honza,

I'm looking over the changes made by more than one of the forks to the project, in particular gchoing and rcaileff.  Gianne took to refactoring and creating structures for the server.  (versus the switch approach).  Gianne also did another brach which was more canonical, but I haven't looked that closely at that branch yet.

Since I'm looking to add a .BitBucketStash entry (since Stash and BitBucketEnterprise are slightly different), and assuming I get it all working correctly, I will make a pull request against your master repo.  ...

Which style of implementation would you prefer?

<pre>
public enum GitServiceType: String {
    case GitHub = "github"
    case BitBucket = "bitbucket"
    case BitBucketEnterprise = "bitbucketenterprise"
    //    case GitLab = "gitlab"
}

public protocol GitService {
    func serviceType() -> GitServiceType
    func prettyName() -> String
    func logoName() -> String
    func hostname() -> String
    func baseURL() -> NSURL
    func authorizeUrl() -> String
    func accessTokenUrl() -> String
    func serviceKey() -> String
    func serviceSecret() -> String
}

public extension GitService {
}

public struct GitHubService: GitService {
    
    public init() {
    }
    
    public func serviceType() -> GitServiceType {
        return .GitHub
    }
    
    public func prettyName() -> String {
        return "GitHub"
    }
  ...
public struct BitBucketService: GitService {
    
    public init() {
    }
    
    public func serviceType() -> GitServiceType {
        return .BitBucket
    }
    
    public func prettyName() -> String {
        return "BitBucket"
    }
  ...  

public struct BitBucketEnterpriseService: GitService {
    public let _baseURL: NSURL
    public init() {
        self.init(baseURL:"")
    }
    
    public init(baseURL: String) {
        self._baseURL = NSURL(string:baseURL)!
    }
    
    public func serviceType() -> GitServiceType {
        return .BitBucketEnterprise
    }
</pre>

versus using a switch wherever necessary...

<pre>
public enum GitService: String {
    case GitHub = "github"
    case BitBucket = "bitbucket"
//    case GitLab = "gitlab"
    
    public func prettyName() -> String {
        switch self {
        case .GitHub: return "GitHub"
        case .BitBucket: return "BitBucket"
        }
    }
    
    public func logoName() -> String {
        switch self {
        case .GitHub: return "github"
        case .BitBucket: return "bitbucket"
        }
    }
    
    public func hostname() -> String {
        switch self {
        case .GitHub: return "github.com"
        case .BitBucket: return "bitbucket.org"
        }
    }
    
    public func authorizeUrl() -> String {
        switch self {
        case .GitHub: return "https://github.com/login/oauth/authorize"
        case .BitBucket: return "https://bitbucket.org/site/oauth2/authorize"
        }
    }
</pre>

**Comment by czechboy0** [comment]
Long term, probably the first one scales better. The second one stemmed from my laziness rather than from a desired design. Thanks!
