### ISSUE TITLE
A way to disable automatic comments

### ISSUE THREAD

**Issue by joelekstrom** [czechboy0/Buildasaur#28]
I'd like a checkbox to prevent Buildasaur from posting stuff in the PR conversation. The build status of the PR is enough for us!

**Comment by czechboy0** [comment]
Ok, I quickly disabled in on [this branch](https://github.com/czechboy0/Buildasaur/tree/hd/feature/no_status_comments). If you can build Builda from code, just use that for now. I'll add it to the UI and stuff next week, but this should get you through in the meantime.

**Comment by joelekstrom** [comment]
Nice! Thanks for the quick update. Buildasaur is really great! :+1:

**Comment by czechboy0** [comment]
Glad you like it, keep the feedback coming!

**Comment by czechboy0** [comment]
@accatyyc Ok it's merged in master. Released in [release 0.2.7](https://github.com/czechboy0/Buildasaur/releases/tag/v0.2.7). Let me know if this works for you.
