### ISSUE TITLE
Trying to sync again...

### ISSUE THREAD

**Issue by reststop** [czechboy0/Buildasaur#288]
After a Syncer has been running for a long time, generally more than a week, I have seen the following error:

**Trying to sync again even though the previous sync hasn't finished. You might want to consider making the sync interval longer. Just sayin'**

This error repeats forever, or until Buildasaur is killed (Did NOT try stopping the Sync and restarting it.  Will try that the next time I see this issue.)

This has occurred at least 2x, possibly more.  Since I am usually running Buildasaur in debug mode, I usually just stop the app and restart it when I check and notice this error is occurring.

In the most recent case, the error occurred just after another error (names sanitized):
(β prefix in msg courtesy of chiong's branch)

[VERBOSE]: SyncPair PR (844:aa/bb) + Bot (β [yy] aa/bb) finished sync after 0.826 seconds.
[ERROR]: Syncing encountered a problem. Error: Failed to post a status (Build passed!) on commit ea0e479b325e9b7e1a3c97216128210b42238515 of repo xx/yy. Context: SyncPair: PR (844:aa/bb) + Bot (β [yy] aa/bb)
[INFO]: Trying to sync again even though the previous sync hasn't finished. You might want to consider making the sync interval longer. Just sayin'

Not sure if this error always occurs after the previous error.  I have seen this error occur, just about any time I try to debug the SyncPair loop.  Usually when stopping at a breakpoint and continuing, it occurs.  If I get a chance, I will try the steps to reproduce that in the next week or so and see if that helps track down the problem.

Reproducing the long-running is only by letting it run a long time.

I didn't see this in your closed/open issues, so I am adding it.
Feel free to rename it if you have a better root cause scenario.

**Comment by reststop** [comment]
Found the following with grep for the error in all current logs
- grep 'Trying to sync again' **Builda.log** | wc -l
  **1003**
- grep 'Trying to sync again' Builda.log2016-05-22T02-45-42 | wc -l
     **3**
- grep 'Trying to sync again' **Builda.log2016-05-26T18-57-00** | wc -l
  **1607**
- grep 'Trying to sync again' Builda.log2016-05-31T17-56-25 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-02T20-30-98 | wc -l
     **2**
- grep 'Trying to sync again' Builda.log2016-06-07T05-55-99 | wc -l
     **0**
- grep 'Trying to sync again' **Builda.log2016-06-07T16-51-27** | wc -l
    **47**
- grep 'Trying to sync again' Builda.log2016-06-08T07-54-63 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-09T06-37-50 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-10T17-35-38 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-11T19-43-91 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-12T16-41-93 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-14T05-58-26 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-16T09-36-39 | wc -l
     **0**
- grep 'Trying to sync again' **Builda.log2016-06-21T21-12-62** | wc -l
   **845**
- grep 'Trying to sync again' Builda.log2016-06-23T08-27-64 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-25T23-12-97 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-27T20-22-02 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-06-30T07-27-96 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-04T19-15-25 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-07T00-30-12 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-09T00-00-56 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-10T04-00-56 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-11T00-55-54 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-12T00-10-47 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-13T00-10-24 | wc -l
     **0**
- grep 'Trying to sync again' Builda.log2016-07-14T03-15-32 | wc -l
     **0**

Logs show prior to the ones with large counts, no indication an error always occurs before this happens...

**Builda.log2016-05-26T18-57-00**
[INFO]: Sync finished successfully at 2016-05-22 16:58:45 +0000, took 0.69 seconds.
**------------------------------------**
[INFO]: Sync starting at 2016-05-22 16:59:44 +0000
**[INFO]: Trying to sync again even though the previous sync hasn't finished. You might want to consider making the sync interval longer. Just sayin'**

**Builda.log2016-06-07T16-51-27**
[INFO]: Sync finished successfully at 2016-06-07 18:29:55 +0000, took 1.423 seconds.
**------------------------------------**
[INFO]: Sync starting at 2016-06-07 18:31:54 +0000
[VERBOSE]: HTTPUtils sendRequest: GET https://myhost
[VERBOSE]: HTTPUtils sendRequest: Optional( ... )
[VERBOSE]: HTTPUtils Response: 401 <NSHTTPURLResponse: 0x628000225b00>
**[INFO]: Trying to sync again even though the previous sync hasn't finished. You might want to consider making the sync interval longer. Just sayin'**

**Builda.log2016-06-21T21-12-62**
[INFO]: Sync finished successfully at 2016-06-18 14:07:21 +0000, took 1.153 seconds.
**------------------------------------**
[INFO]: Sync starting at 2016-06-18 14:12:20 +0000
[VERBOSE]: HTTPUtils sendRequest: GET https://myhost
[VERBOSE]: HTTPUtils sendRequest: Optional()
[ERROR]: Syncing encountered a problem. Error: The request timed out.. Context: Fetching Repo
[INFO]: Sync finished with error at 2016-06-18 14:12:35 +0000, took 14.763 seconds.
**------------------------------------**
[INFO]: Sync starting at 2016-06-18 14:17:20 +0000
[VERBOSE]: HTTPUtils sendRequest: GET https://myhost
[VERBOSE]: HTTPUtils sendRequest: Optional()
[VERBOSE]: HTTPUtils Response: 401 <NSHTTPURLResponse: 0x6100000372c0>
**[INFO]: Trying to sync again even though the previous sync hasn't finished. You might want to consider making the sync interval longer. Just sayin'**

**Comment by czechboy0** [comment]
This looks like the GitHub server or the Xcode Server are taking a long time to respond. This isn't really an issue, it's just informing you that each sync takes longer than expected, not allowing for the specified sync frequency. Feel free to take a look, but I doubt it's an issue in Buildasaur - and again, it's not an error, just an info log. Please open if you find some evidence of it being an issue with Buildasaur.

**Comment by reststop** [comment]
Hi Honza,

Yes, I would agree, if the warning came out only once, but that's not the case.  The point of this report is that the syncer seems to stop working and the info message repeats forever.  I just never had the time to do much investigating.

If I kill Buildasaur and restart it, the problem vanishes immediately.

In the log files I showed excerpts from, once the Info message started, it appears stuck in a loop with no more processing and each time a syncer run was supposed to occur, it just outputs the info message, and never recovers.

I showed the logs with the messages leading up to the error given in the hopes it might shed some light on what was happening before the error (the message repeating).  Once that message printed out, it continuously kept just printing that message and nothing else.  The message just repeats hundreds or thousands of times (depending on how long it ran before I noticed it and killed it).

Each time I've seen it happen it was running overnight, and I would see the error and kill Buildasaur and restart it to get things back to running again.

I attached the grep | wc -l just to identify which logs to review.  The ones with less than 10 messages, were as you say, just info, and the next time through the syncer went as expected.  The ones with more than 100 (plus the ne with 47) were all cases where it seemed to start repeating forever.

Fine to close this for now, and when it occurs again in a week or so, I'll try to get more information, such as whether it will reset if I stop/start the syncer, or if the info message just loops, or prints out every "n" seconds each time the syncer is supposed to run.  If time permits, I may put in a breakpoint or two and see if I can identify where it's looping or what it's checking to decide that it is taking too long to do a sync.  SInce it has happened 4+ times I expect it will recur again.

As mentioned in one of the posts, whenever I tried debugging the syncer loop and stopped at any breakpoint, when I told it to proceed from the breakpoint, I would see that message, and that is repeatable.  I'll write up exactly the steps to reproduce that in a followup to this issue.

-Carl

**Comment by czechboy0** [comment]
Yes, if you put a breakpoint and hold the syncer, it will print this message - that's how this info message works. It records the time at the start of the sync and if it finishes after it was supposed to start the next sync, it prints this. So it's expected to happen while debugging.

Regarding the cases when this happens overnight, I wonder if it isn't completely stuck, waiting for some resource. Another possibility is that the forked version changed the logic and some completion block isn't getting called, making Buildasaur think that the sync is still happening.

Either way, it'd be great if you could reproduce it on this mainline version of Buildasaur, because I can't spend time hunting for bugs in the fork, where I have no idea what changes were made there.
