### ISSUE TITLE
Custom post-integration actions

### ISSUE THREAD

**Issue by seanlabastille** [czechboy0/Buildasaur#292]
Once an integration completes it may have produced several artefacts, including:
- Logs for all build phases
- Archives
- Executables

These can be retrieved using the Xcode Server API as a ZIP archive hosted at `/xcode/internal/api/integrations/:integration/assets`.

The archive looks roughly as follows:

```
Assets
├── Session-Tests-2016-08-23_144829-3grM0e.log
├── buildService.log
├── sourceControl.log
├── trigger-after-0.log
├── trigger-after-1.log
├── trigger-before-0.log
├── xcodebuild.log
└── xcodebuild_result.bundle.zip
```

Since there are various issues related to exposing Xcode Server to the internet it would seem easier to allow custom actions to process these archives, for example for placing them in a suitable location when direct access to Xcode Server is not possible.

At first glance this could be an extension of the `Actions` struct in `SyncPair` to specify a shell script that is given the path to the ZIP archive.

**Comment by czechboy0** [comment]
You should be able to do anything you want in a post-build script: https://honzadvorsky.com/articles/2015-08-17-17-30-xcode_server_tutorials_3_prebuild__postbuild_scripts/

**Comment by seanlabastille** [comment]
@czechboy0 I'll need to double-check that. I'm not sure if the ZIP is already available at that stage. Because the post-integration trigger logs are also included there.

**Comment by czechboy0** [comment]
Not sure which zip you mean exactly, but everything is accessible from the script, as it runs _after_ the build completes. Just add a post-build script with `set` so you get all env vars printed out and can see what's available (all of the Xcode Server ones have the prefix `XCS_`)
