### ISSUE TITLE
Setup questions?

### ISSUE THREAD

**Issue by pajapro** [czechboy0/Buildasaur#293]
Hi @ioveracker, @accatyyc and other maintainers,

I have a few questions and thought I will form them into one Github issue:
1. With the latest Xcode Server 8, one creates "CI user" account in order to have separated environment. Am I suppose to install and run Buildasaur from the "CI user" account or from administrator account?
2. I managed to setup a bot for one of my project where I use cocoapods. I configured trigger like this:
   ![screen shot 2016-10-08 at 23 59 32](https://cloud.githubusercontent.com/assets/16186868/19216211/460c9bd4-8db3-11e6-97b6-b34cdedddc60.png)
   In order to ensure my pods are fetched and .xcworkspace created. However, Builda fails because `"xcodebuild: error 'pathToProject/My Project.xcworkspace" does not exist`\- assume that this happens because `pod install` (before trigger) was not executed.

**Comment by seanlabastille** [comment]
Regarding the CI user it is probably a better idea _not_ to run Buildasaur using that user. Keeping that account only for builds makes it easier to isolate issues and if necessary recreate the account without losing your Buildasaur setup.

Unless you have the `.bash_profile` for the CI user configured to include CocoaPods in its `$PATH` you are better off setting this explicitly at the top of your trigger script.

It can help to run `ls -R` or `tree` to figure out what the result of the clone was and then adjust your paths from there.

**Comment by pajapro** [comment]
> Regarding the CI user it is probably a better idea not to run Buildasaur using that user. Keeping that account only for builds makes it easier to isolate issues and if necessary recreate the account without losing your Buildasaur setup.

Good point and thanks for advise.

It also solved the Cocoapods issue. One more question @flufff42, why does Builda need Github access token when creating a new syncer? Shouldn't the SSH keys be enough?

**Comment by seanlabastille** [comment]
Using an API token allows Buildasaur to [update the pull request being integrated with the build status](https://github.com/buildasaurs/Buildasaur#envelope-posting-status-comments).
