### ISSUE TITLE
Build Template Settings has no schemes in dropdown

### ISSUE THREAD

**Issue by mikewoodworth** [czechboy0/Buildasaur#38]
This is building with an xcworkspace, none of the schemes show up in template settings

**Comment by czechboy0** [comment]
Can you make sure your scheme is shared? Otherwise Buildasaur won't be able to find it. You can share a scheme in Xcode, Manage Schemes. More [here](https://developer.apple.com/library/ios/recipes/xcode_help-scheme_editor/Articles/SchemeManage.html).

Let me know if this helps. Otherwise it might be a genuine Buildasaur issue, thanks!

**Comment by mikewoodworth** [comment]
Yes, scheme is shared...

![screen shot 2015-05-12 at 12 19 46 pm](https://cloud.githubusercontent.com/assets/208050/7596259/458a0820-f8a1-11e4-9922-50e310883487.png)

Let me know if there's anything I can provide to help debug!

**Comment by czechboy0** [comment]
Oh I see, I don't think I've tested with the scheme being in the workspace instead of the project, let me try to reproduce it locally.

**Comment by mikewoodworth** [comment]
Yea, I can confirm the scheme shows up if I set to project. Trying that now

**Comment by czechboy0** [comment]
Yes, it doesn't pick it up if it's owned by the workspace. I'll look at it, thanks for reporting it! In the meantime, I'd suggest just selecting the scheme to be owned by the project, if that's possible. I'll try to push a fix ASAP.

Did you download Builda as .app or as code? To know whether a new release with the fix will need to be made :)

//Edit - just saw your reply. Yeah I'll fix it for workspaces as well but if you could use it in the project that'd fix it for now.

**Comment by mikewoodworth** [comment]
Yea, I've switched to project all is fine. Thanks for the fast response!

**Comment by czechboy0** [comment]
Actually, I fixed it in #39. Thanks again for reporting!

**Comment by mikewoodworth** [comment]
Quick followup...
My bots are all failing with:

Bot Issue: error. Build Service Error.
Issue: Failed to authenticate SSH session: Invalid public key, too short (-1).
Integration Number: 1.
Integration URL: https://DMTestBot.local/xcode/bots/B2E8D9D/integrations
Description: Failed to authenticate SSH session: Invalid public key, too short (-1).

Any chance this is related to the fact I pointed buildasaur at the xcworkspace instead of the project? Both the top left and right say Verified access, all is well!

The same ssh keys are working just fine in the actual repo on this machine.

**Comment by czechboy0** [comment]
Can you please copy this to #30? I'm actually working on validation of SSH keys as we speak :) We can discuss there, thanks.
