### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by czechboy0** [czechboy0/Buildasaur#44]
Plus show it in the UI together with a button to download it.

**Comment by czechboy0** [comment]
Probably something like pulling of the latest release metadata from GitHub once a day and comparing it to the currently running version.

**Comment by joelekstrom** [comment]
https://github.com/sparkle-project/Sparkle

**Comment by czechboy0** [comment]
Interesting, I actually meant just checking for a new version, but automatic updating might be even better. Thanks, @accatyyc, I'll take a look at how difficult it is to integrate.

**Comment by czechboy0** [comment]
How about: http://devmate.com ?

**Comment by joelekstrom** [comment]
IMO seems like a bit too much - looks perfect if you want to sell licenses etc, but for an open source project like this?

**Comment by czechboy0** [comment]
Yeah I wouldn't need that. But crash reporting, some basic stats and automatic updates are what I'm looking for.

**Comment by joelekstrom** [comment]
Okay. Try it but watch out for the costs! There may be more than 1000 users. No way to know though. Otherwise, Google Analytics is free for a lot more users, but doesn't have crash reporting though.

Do you think the automatic crash reporting is needed? The users of this app are technical, and probably keen to report crashes anyway.

**Comment by czechboy0** [comment]
I agree, but even for technical users I'm trying to provide the simplest possible experience. 

I would prefer to not use Google Analytics, but I might just use Crashlytics for crashes and Sparkle for updating. I just liked the appeal of how this easily this can be integrated, because honestly I don't want to spend much time on these things, but I'd like to have at least a rough idea of how many people use it, how much it crashes and make it very easy to update - starting from 1.0. 

People will always be able to build it from code. But also I'd like to attract users who just have an Xcode Server and don't know much about how this all works - to just download the binary, set it up and launch it.

**Comment by czechboy0** [comment]
Fixed by #230
