### ISSUE TITLE
It is not possible to edit trigger scripts inline

### ISSUE THREAD

**Issue by st3fan** [czechboy0/Buildasaur#58]
I'm trying to edit a trigger script but when i type a return, the text field 'submits' instead of inserting a newline.

**Comment by czechboy0** [comment]
Use Option + Enter in the meantime, I'm fixing it.

**Comment by czechboy0** [comment]
@st3fan Ok, fix merged in master. Let me know if you need a .app to download instead of building from code yourself.

**Comment by st3fan** [comment]
Thanks! No worries, i'll wait for the next release. I worked around this by copy/paste from external editor.
