### ISSUE TITLE
Extract BuildaCiServer

### ISSUE THREAD

**Issue by cojoj** [czechboy0/Buildasaur#63]
I'd be really nice to extract whole `BuildaCIServer` to separate framework. Also CocoaPods and Carthage support are welcome.

I think that this implementation bring a lot of possibilities as you've captured a big part of Xcode Bots API in a nice container called `XcodeServer`.

A lot of people can take benefit from this and create other tools allowing them to use Xcode Bots from the outside of Xcode.

**Comment by czechboy0** [comment]
Resolved: https://github.com/czechboy0/XcodeServerSDK
