### ISSUE TITLE
Incorrect comment info 

### ISSUE THREAD

**Issue by valeriomazzeo** [czechboy0/Buildasaur#82]
When manually triggering an integration on the pull requests bot (no code changes between the first integration and the manual one being triggered), buildasaur post on GitHub a comment with the info about the first integration instead than about the last one.

The same happens when triggering a third integration manually.

I am almost sure this is caused by having no code changes in between those integration.

**Comment by czechboy0** [comment]
Interesting, I'll try to reproduce. It should always report the status of the _last_ integration for the commit, but possibly there's a bug. Thanks for reporting, I'll get back once I know what's up.

**Comment by valeriomazzeo** [comment]
thanks for looking into it :+1:

**Comment by czechboy0** [comment]
Hmm, it seems to work as expected to me. Every time I manually kick off an integration from Xcode, a new comment is posted on GitHub afterwards with the result of the _latest_ integration. Each of these comments starts with **Result of integration 1** then 2 and 3... And this number should go up with every new integration. I tried it here, you can see that no commits have been pushed between those comments but the last 3 always report the right integration's result ([this is my sandbox repo](https://github.com/czechboy0/Buildasaur-Tester/pull/2)).

Can you please provide a bit more information? How do you know the result is stale? Does Buildasaur post multiple comments starting with the same number in **Result of integration NUMBER**? Can you maybe provide a screenshot or any piece of log? Thanks!

**Comment by valeriomazzeo** [comment]
This is what happened:

![schermata 2015-07-13 alle 23 20 54](https://cloud.githubusercontent.com/assets/1882080/8662250/c2663054-29b5-11e5-9bcc-bbdbc67b9d7d.png)

**Comment by valeriomazzeo** [comment]
This is what happened:

![schermata_2015-07-13_alle_23_20_54](https://cloud.githubusercontent.com/assets/1882080/8662324/587da0d6-29b6-11e5-9007-eafc213455be.png)

In that bot the first integration, well you can see the results: the simulator timed out.
The second one was actually ok, but buildasaur kept printing the result of the first.

**Comment by czechboy0** [comment]
I don't suppose you still have those integrations on your server and could send me a JSON to test with? :frowning: This looks like a bug, but it's very weird that it is happening. I can't reproduce it or see in code how this could happen other than by deleting the previous integration/bot on the server. This definitely should not happen when relaunching an integration on the same code.

**Comment by valeriomazzeo** [comment]
Buildasaur deleted the integration for that PR so the answer is no :(

Unless there is a log on buildasaur that can be helpful to you?

**Comment by czechboy0** [comment]
Buildasaur should only delete `Bots` (the build job description, is tied to one branch). And it starts an `Integration` (one run of the build job, which has a result and a number).

Let me know if you can think of a way to reproduce it. I'd really like to track this one down. Thanks!

**Comment by valeriomazzeo** [comment]
Sorry, I didn't word it correctly. It deleted the bot.

Just to make sure, in case it happens again what log file would be useful to you?

**Comment by czechboy0** [comment]
Hmm in case you still have it, getting the output from `https://XCODE_SERVER_IP:20343/api/integrations` would be most useful, followed by the log file in `~/Library/Application Support/Buildasaur/Builda.log`

**Comment by czechboy0** [comment]
@valeriomazzeo Sorry, I can't reproduce it. If this ever happens again, feel free to comment and provide some logs or any more details and I'll reopen this issue.

**Comment by valeriomazzeo** [comment]
sure, no problem :+1:

to be honest it's not happening all the time, but as long as I spot it I will provide some logs :)
