### ISSUE TITLE
Run on start

### ISSUE THREAD

**Issue by valeriomazzeo** [czechboy0/Buildasaur#83]
When the server running buildasaur is restarted, there is no way to have buildasaur running without manual intervention.

Even when automatically login with an user and having buildasaur in the launch items we have to click on three buttons: Xcode server config, github config and start to have buildasaur working.

This is not the best situation in an automated environment.

Possibly related to #80

**Comment by czechboy0** [comment]
Yup, definitely a subset of #80.
